// <auto-generated />
namespace UHRMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Removed_RequiredFilter_From_BoardingForm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removed_RequiredFilter_From_BoardingForm));
        
        string IMigrationMetadata.Id
        {
            get { return "201904250236463_Removed_RequiredFilter_From_BoardingForm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
